apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-csi-rbd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ceph.github.io/csi-charts
    chart: ceph-csi-rbd
    targetRevision: 3.13.0
    helm:
      valuesObject:
        csiConfig:
          - clusterID: "proxmox-ceph"
            monitors:
              - "192.168.0.150:6789"
        secret:
          create: false
          name: csi-rbd-secret
        storageClass:
          create: true
          name: ceph-rbd
          clusterID: proxmox-ceph
          pool: kubernetes
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFeatures: layering
  destination:
    server: https://kubernetes.default.svc
    namespace: ceph-csi
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
