---
# テスト用のPersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-rbd-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Gi
---
# テスト用のPod
apiVersion: v1
kind: Pod
metadata:
  name: ceph-rbd-test-pod
  namespace: default
spec:
  containers:
    - name: test
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "echo 'Hello from Ceph!' > /mnt/test.txt && cat /mnt/test.txt && sleep 3600"]
      volumeMounts:
        - name: ceph-volume
          mountPath: /mnt
  volumes:
    - name: ceph-volume
      persistentVolumeClaim:
        claimName: ceph-rbd-test-pvc
