apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana-community.github.io/helm-charts
    chart: grafana
    targetRevision: 11.3.7
    helm:
      valuesObject:
        # PV が未整備のため永続化を無効化
        # PV を用意したら enabled: true に変更する
        persistence:
          enabled: false

        # Prometheus をデータソースとして自動登録
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                isDefault: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
