apiVersion: v1
kind: PersistentVolume
metadata:
  name: hollo-pg-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  # claimRef:
  #   namespace: app-hollo
  #   name: hollo-pg-1
  local:
    path: /mnt/local-storage/hollo-pg
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - microk8s-controller-1
