apiVersion: v1
kind: Service
metadata:
  name: playwright
  namespace: app-open-webui
spec:
  selector:
    app: playwright
  ports:
    - protocol: TCP
      port: 3000
      targetPort: ws
      name: websocket
