apiVersion: apps/v1
kind: Deployment
metadata:
  name: element
  namespace: app-matrix
  labels:
    app: element
spec:
  replicas: 1
  selector:
    matchLabels:
      app: element
  template:
    metadata:
      labels:
        app: element
    spec:
      containers:
        - name: element
          # ref: https://github.com/element-hq/element-web/pkgs/container/element-web/versions?filters[version_type]=tagged
          image: ghcr.io/element-hq/element-web@sha256:f4a81a24d49a9c5b97e02e77a3013ec799873e500e69041078a28be98e4f1280 # v1.12.17
          env:
            - name: ELEMENT_WEB_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /app/config.json
              subPath: config.json
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      volumes:
        - name: config
          configMap:
            name: element-config
