apiVersion: apps/v1
kind: Deployment
metadata:
  name: element
  namespace: app-matrix
  labels:
    app: element
spec:
  replicas: 1
  selector:
    matchLabels:
      app: element
  template:
    metadata:
      labels:
        app: element
    spec:
      containers:
        - name: element
          image: ghcr.io/element-hq/element-web:latest
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: /app/config.json
              subPath: config.json
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      volumes:
        - name: config
          configMap:
            name: element-config
