apiVersion: v1
kind: PersistentVolume
metadata:
  name: continuwuity-data
  labels:
    app: continuwuity
    type: data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    namespace: app-matrix
    name: continuwuity-data
  local:
    path: /mnt/local-storage/continuwuity-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - microk8s-controller-1
