apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: 0.13.0
  destination:
    server: https://kubernetes.default.svc
    namespace: app-arc
  syncPolicy:
    automated:
    syncOptions:
      - ServerSideApply=true # metadata.annotations: Too long: must have at most 262144 bytes を避けるため
