apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-pages-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    namespace: app-git-pages
    name: git-pages-pvc
  local:
    path: /mnt/local-storage/git-pages
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - microk8s-controller-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-pages-pvc
  namespace: app-git-pages
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
