apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-openclaw
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/umee-sh/homelab.git
    path: argocd/openclaw
    targetRevision: main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
