apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-pg-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    namespace: app-forgejo
    name: forgejo-pg-1
  local:
    path: /mnt/local-storage/forgejo-pg
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - microk8s-controller-1

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-pg
  namespace: app-forgejo
spec:
  instances: 1

  # リストア
  # bootstrap:
  #   recovery:
  #     source: backup
  # externalClusters:
  #   - name: backup
  #     barmanObjectStore:
  #       endpointURL: "https://s3.isk01.sakurastorage.jp"
  #       destinationPath: s3://i544c-me--learn-microk8s/hollo-backup/
  #       serverName: hollo-pg
  #       s3Credentials:
  #         accessKeyId:
  #           name: sakura-obj-credentials
  #           key: ACCESS_KEY_ID
  #         secretAccessKey:
  #           name: sakura-obj-credentials
  #           key: SECRET_ACCESS_KEY
  #       data:
  #         compression: gzip
  #       wal:
  #         compression: gzip

  storage:
    storageClass: local-storage
    size: 1Gi

  backup:
    barmanObjectStore:
      endpointURL: "https://s3.isk01.sakurastorage.jp"
      destinationPath: s3://i544c-me--learn-microk8s/forgejo-pg-backup/
      serverName: forgejo-pg
      s3Credentials:
        accessKeyId:
          name: sakura-obj-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: sakura-obj-credentials
          key: SECRET_ACCESS_KEY
      data:
        compression: gzip
      wal:
        compression: gzip
    retentionPolicy: "7d"

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: forgejo-pg-backup
  namespace: app-forgejo
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: forgejo-pg
