name: CI

on:
  push:
    branches: [main]
    paths:
      - 'argocd/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'argocd/**'
      - '.github/workflows/**'

jobs:
  kubeconform:
    name: Kubernetes Manifest Validation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6

      - name: Install kubeconform
        run: |
          curl -sSLo kubeconform.tar.gz \
            "https://github.com/yannh/kubeconform/releases/download/v0.8.0/kubeconform-linux-amd64.tar.gz"
          echo "9bc2bffbf71f261128533edaf912153948b7ff238f9a531ae6d34466ec287883  kubeconform.tar.gz" | sha256sum -c
          tar xz -C /usr/local/bin -f kubeconform.tar.gz

      - name: kubeconform
        run: |
          find argocd -name '*.yaml' | \
          xargs kubeconform \
            --strict \
            --ignore-missing-schemas \
            --kubernetes-version 1.31.0 \
            --summary
